### ISSUE TITLE
file_input template includes imfile, so cannot by reused

### ISSUE THREAD

**Issue by luckymike** [sous-chefs/rsyslog#119]
### Cookbook version
4.0.1
### Chef-client version
12.15.19

### Platform Details
Ubuntu 16.04 on AWS

### Scenario:
Can't call the `file_input` resource multiple times with the default template. The config test added in 4.0.1 will fail b/c imfile is included multiple times.

### Steps to Reproduce:
Create multiple `ryslog_file_input` resources using the default template.

### Expected Result:
Successful converge.

### Actual Result:
```
[2016-11-02T21:03:43+00:00] ERROR: Exception handlers complete
ERROR: execute[validate_config] (rsyslog::default line 42) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of rsyslogd -N 1 -f /etc/rsyslog.conf ----
STDOUT:
rsyslogd: version 8.16.0, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: module 'imfile' already in this config, cannot be added  [v8.16.0 try http://www.rsyslog.com/e/2221 ]
rsyslogd: module 'imfile' already in this config, cannot be added  [v8.16.0 try http://www.rsyslog.com/e/2221 ]
---- End output of rsyslogd -N 1 -f /etc/rsyslog.conf ----
Ran rsyslogd -N 1 -f /etc/rsyslog.conf returned 1
[2016-11-02T21:03:43+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

The input_file template included in the cookbook should not include imfile or should have some conditional logic to ensure it's only included in one of them. It might make sense to have a dedicated file in `/etc/rsyslog.d` to include `imfile` that is created anytime the `ryslog_file_input` resource is used.

**Comment by luckymike** [comment]
@tas50, I'd be happy to submit a PR for this, if you can give me a thumbs-up on the approach.

My inclination would be to have a helper file that does nothing more than include `imfile` and call that `file` resource conditionally in the `file_input` resource.

**Comment by growak** [comment]
@luckymike @tas50 Is there a PR opened for this bug ?
Thank you guys !

**Comment by tas50** [comment]
I’m adding the Type: Jump In GitHub label to this issue. This is a great issue for someone to get their feet wet with and we’d love a PR to resolves the issue.

**Comment by runswithd6s** [comment]
@tas50 I think I have a work-able solution in #151. Please take a look and let me know if you need any changes. The `spec` tests can use some work. SmartOS should be version 5.1, and it doesn't look like `chefspec/fauxhai` supports Omnios any longer.
