### ISSUE TITLE
el6 using imjournal and OmitLocalLogging

### ISSUE THREAD

**Issue by bcg62** [sous-chefs/rsyslog#188]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

centos6 is loding imjournal and OmitLocalLogging which breaks local logging. IE logger.

## :pancakes: Cookbook version

9.0.0

## :woman_cook:  Chef-Infra Version

15.10.12.

## :tophat: Platform details

centos 6.10

## Steps To Reproduce

converge on el6

## :police_car: Expected behavior

imjournal not to be used as there is no journal,  OmitLocalLogging should not be enabled.

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by bcg62** [comment]
https://github.com/sous-chefs/rsyslog/commit/82062df981661483c23af45b6e5508fa4f0453aa#diff-030d34d25500e7467089d4e90fa949f3f27db2f89e1f47ba7a36de7c02e95748L149

**Comment by ramereth** [comment]
This cookbook no longer supports running on EL6 which has been EOL. You're welcome to use a previous version which does still have support. Thanks-
